intensity_filter_chain:
  ros__parameters:
    name: intensity_threshold
    type: laser_filters/LaserScanIntensityFilter
    params: 
      lower_threshold: 0.5
      upper_threshold: 3.0
      disp_histogram: 1

bad_filter_chain:
  ros__parameters:
    name: dark_shadows
    type: laser_filters/LaserScanIntensityFilter
    params:
      lower_threshold: 0.5
      upper_threshold: 3.0
      disp_histogram: 0

interp_filter_chain:
  ros__parameters:
    name: interpolation
    type: laser_filters/InterpolationFilter

shadow_filter_chain:
  ros__parameters:
    name: shadows
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 80.0
      max_angle: 100.0
      neighbors: 1
      window: 1

array_filter_chain:
  ros__parameters:
    type: laser_filters/LaserArrayFilter
    name: laser_median_filter
    params: 
      range_filter_chain:
        name: median_2
        type: filters/MultiChannelMeanFilterFloat 
        params:
          number_of_observations: 3
      intensity_filter_chain:
        name: median_2
        type: filters/MultiChannelMeanFilterFloat
        params:
          number_of_observations: 3

mask_filter_chain:
  ros__parameters:
    name: mask
    type: laser_filters/LaserScanMaskFilter
    params:
      masks:
        laser: [1, 5]
